import Header from '../components/header'
import Footer from '../components/footer'
import './globals.css'
import { Poppins } from '@next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Header/>
        <main>{children}</main>
        <Footer/>
        </body>
    </html>
  )
}
